global:
  query_log_file: "prometheus.log"
  external_labels:
    env: test
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "localhost:9093"

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node"
    basic_auth:
      username: "lhq"
      password: "123456"
    file_sd_configs:
      - files:
        - sd/file/node/*.yaml
        - sd/file/node/*.json

      #v1:
      #static_configs:
      #- targets:
          #- "localhost:9100"
