groups:
  - name: target
    rules:
      - alert: target is down
        expr: up == 0
        for: 1m
        labels:
          level: heigh
        annotations:
          summary: "节点离线"
          description: "节点离线了"